// luagen.mjs — serialize the data model into KeyLevelLogs/Data.lua.
// Deterministic output (sorted keys) so regenerated files diff cleanly.

const LUA_IDENT = /^[A-Za-z_][A-Za-z0-9_]*$/;
const LUA_KEYWORDS = new Set([
  "and", "break", "do", "else", "elseif", "end", "false", "for", "function",
  "if", "in", "local", "nil", "not", "or", "repeat", "return", "then",
  "true", "until", "while",
]);

export function luaString(s) {
  return '"' + String(s).replace(/[\\"\n\r\0]/g, (ch) => ({
    "\\": "\\\\",
    '"': '\\"',
    "\n": "\\n",
    "\r": "\\r",
    "\0": "\\000", // 3 digits: lua's \ddd escape would swallow a following digit
  }[ch])) + '"';
}

function luaKey(k) {
  // canonical numeric keys become [123]; "012"-style strings must stay
  // strings or they'd collide with the number 12
  if (typeof k === "number") return `[${k}]`;
  if (/^-?\d+$/.test(k) && String(Number(k)) === k) return `[${k}]`;
  if (LUA_IDENT.test(k) && !LUA_KEYWORDS.has(k)) return k;
  return `[${luaString(k)}]`;
}

function luaValue(v, indent) {
  if (v === null || v === undefined) return "nil";
  switch (typeof v) {
    case "number":
      if (!Number.isFinite(v)) throw new Error(`non-finite number in data: ${v}`);
      return Number.isInteger(v) ? String(v) : String(Math.round(v * 10) / 10);
    case "boolean":
      return v ? "true" : "false";
    case "string":
      return luaString(v);
    case "object":
      return luaTable(v, indent);
    default:
      throw new Error(`cannot serialize ${typeof v} to lua`);
  }
}

function sortedKeys(obj) {
  return Object.keys(obj).sort((a, b) => {
    const na = Number(a), nb = Number(b);
    const aNum = !Number.isNaN(na), bNum = !Number.isNaN(nb);
    if (aNum && bNum) return na - nb;
    if (aNum) return -1;
    if (bNum) return 1;
    return a < b ? -1 : a > b ? 1 : 0;
  });
}

export function luaTable(obj, indent = "") {
  const inner = indent + "  ";
  if (Array.isArray(obj)) {
    if (obj.length === 0) return "{}";
    const items = obj.map((v) => inner + luaValue(v, inner));
    return "{\n" + items.join(",\n") + ",\n" + indent + "}";
  }
  const keys = sortedKeys(obj).filter((k) => obj[k] !== undefined);
  if (keys.length === 0) return "{}";
  const items = keys.map((k) => `${inner}${luaKey(k)} = ${luaValue(obj[k], inner)}`);
  return "{\n" + items.join(",\n") + ",\n" + indent + "}";
}

// model: { meta, dungeons, players } (see KeyLevelLogs/Data.lua for shape)
export function generateDataLua(model) {
  const header = [
    "-- Data.lua — GENERATED by the KeyLevelLogs companion. Do not edit by hand.",
    `-- generated: ${model.meta?.generatedAt ?? "unknown"}`,
    "-- /reload in game after this file changes.",
    "",
  ].join("\n");
  return header + "KeyLevelLogsData = " + luaTable(model) + "\n";
}
